version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=polls
    volumes:
      - polls_pg_data:/bitnami/postgresql
    networks:
      - api-polls

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - 'polls_redis_data:/bitnami/redis/data'
    networks:
      - api-polls

  api-polls:
    build:
      context: .
    container_name: api-polls
    ports:
      - '3000:3333'
    environment:
      - DATABASE_URL=postgresql://docker:docker@postgres:5432/polls?schema=public
    depends_on:
      - postgres
      - redis
    networks:
      - api-polls

networks:
  api-polls: 

volumes:
  polls_pg_data:
  polls_redis_data: